apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.configMap.name }}
data:
  timezone: {{ .Values.timezone }}

  grant_all.xml: |-
{{ required "Error: grant_all.xml file is missing!" (.Files.Get "files/clickhouse/users.d/grant_all.xml") | indent 4 }}

  config.xml: |-
{{ required "Error: config.xml file is missing!" (.Files.Get "files/clickhouse/config.xml") | indent 4 }}

  macros.xml: |-
{{ required "Error: macros.xml file is missing!" (.Files.Get "files/clickhouse/config.d/macros.xml") | indent 4 }}

  site-remote-server.xml: |
    <clickhouse>
      <remote_servers replace="true">
        <central_cluster_primery>
            <shard>
                <replica>
                  <host>{{ .Values.clickhouse.centralHostName }}</host>
                  <port>9000</port>
                  <user>{{ .Values.clickhouse.rootUserName }}</user>
                  <password>{{ .Values.clickhouse.rootPassword }}</password>
                </replica>
            </shard>
        </central_cluster_primery>
      </remote_servers>
    </clickhouse>
  
  central-remote-server.xml : |
    <clickhouse>
      <remote_servers replace="true">
        <central_cluster_primery>
{{- range $nodeName, $content := .Values.machines }}
  {{- if $content.clickhouse.enabled }}
    {{- if eq $content.clickhouse.type "site" }}
          <shard>
            <replica>
              <host>{{ $.Values.clickhouse.appName }}-{{ $nodeName }}-headless</host>
              <port>9000</port>
              <user>{{ $.Values.clickhouse.rootUserName }}</user>
              <password>{{ $.Values.clickhouse.rootPassword }}</password>
            </replica>
          </shard>
    {{- end }}
  {{- end }}
{{- end }}
        </central_cluster_primery>
      </remote_servers>
    </clickhouse>

{{- range $nodeName, $content := .Values.machines }}
{{- if $content.clickhouse.enabled }}
  {{ $nodeName }}-network-and-logging.xml: |
    <clickhouse>
      <logger>
        <level>debug</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
      </logger>
      <display_name>{{ $nodeName }}</display_name>
      <listen_host>0.0.0.0</listen_host>
      <http_port>8123</http_port>
      <tcp_port>9000</tcp_port>
      <interserver_http_port>9009</interserver_http_port>
    </clickhouse>
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.configMap.siteInitScripts }}
data:
{{- $files := .Files.Glob "files/clickhouse/site-initdb.d/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | toString | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.configMap.centralInitScripts }}
data:
{{- $files := .Files.Glob "files/clickhouse/central-initdb.d/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | toString | indent 4 }}
{{- end }}